// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// forecasting_ga
NumericVector forecasting_ga(Function evalFunc, int chsize, DoubleVector minv, DoubleVector maxv, double crossprob, double mutationprob, double forecastprob, int elitism, int popsize, int maxiter, int MinimumForecastLength, Function ForecastFunction);
RcppExport SEXP forega_forecasting_ga(SEXP evalFuncSEXP, SEXP chsizeSEXP, SEXP minvSEXP, SEXP maxvSEXP, SEXP crossprobSEXP, SEXP mutationprobSEXP, SEXP forecastprobSEXP, SEXP elitismSEXP, SEXP popsizeSEXP, SEXP maxiterSEXP, SEXP MinimumForecastLengthSEXP, SEXP ForecastFunctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type evalFunc(evalFuncSEXP);
    Rcpp::traits::input_parameter< int >::type chsize(chsizeSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type minv(minvSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type maxv(maxvSEXP);
    Rcpp::traits::input_parameter< double >::type crossprob(crossprobSEXP);
    Rcpp::traits::input_parameter< double >::type mutationprob(mutationprobSEXP);
    Rcpp::traits::input_parameter< double >::type forecastprob(forecastprobSEXP);
    Rcpp::traits::input_parameter< int >::type elitism(elitismSEXP);
    Rcpp::traits::input_parameter< int >::type popsize(popsizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type MinimumForecastLength(MinimumForecastLengthSEXP);
    Rcpp::traits::input_parameter< Function >::type ForecastFunction(ForecastFunctionSEXP);
    __result = Rcpp::wrap(forecasting_ga(evalFunc, chsize, minv, maxv, crossprob, mutationprob, forecastprob, elitism, popsize, maxiter, MinimumForecastLength, ForecastFunction));
    return __result;
END_RCPP
}
